### ISSUE TITLE
Add a parameter to disable adding to the .gitignore

### ISSUE THREAD

**Issue by lsmgeb89** [hedronvision/bazel-compile-commands-extractor#59] opened 2022-06-18 00:38 UTC
Thanks for building this.
I am trying to use this in my workspace.
I see the function `_ensure_gitignore_entries` will automatically add stuff in the `.gitignore` file.

It will be appreciated if we could have a parameter to control this behavior.
It might make sense in your environment. But it might not in others.
For example, our `.gitignore` already ignored `compile_commands.json` and I don't use `clangd` directly.
So for me, I just need to ignore the `external` directory.

**Comment by cpsauer** [comment] 2022-06-21 03:44
Hello again, Siming!
Thanks for writing in and for thinking about ways to make the tool better.

For this one, would it work to just commit the entries and ignore the ones you don't need?

Obviously we can add this feature if needed (or take a PR), but I'm not yet convinced that it's better than just having the one extra entry unused in .gitignore. I thinking that you probably need/want three out of the four (bazel output symlinks, external, and compile_commands.json); and that ignoring /.cache/ shouldn't do much harm but will make things work automagically if you do ever use clangd.  You should be able to delete/change the comments or move the lines around; it only re-adds patterns that it doesn't detect (verbatim) in the .gitignore. My concern with adding the feature is that manual configuration doesn't seem much better or easily discoverable--you'll still need to check configuration into your repo!--and most users will need at least some entries added. If there were an easy way to only auto-add once, so we don't insist if the user deletes the entries, I'd be interested in that, but then we'd have to check in that already-added-entries state, which doesn't seem better.

If I've missed something, though, like that you actively need/want to check in the files that we're ignoring, or if you still feel strongly or want to discuss more, please say!

Cheers--and thanks again for thinking about ways to make this tool better!
Chris

**Comment by lsmgeb89** [comment] 2022-06-21 18:21
I only need to ignore one which is external. Bazel output has already in the `.gitignore`.

I think it's still needed.
The problem is it is not a small personal repository I can control and decide everything.
Image it is a large repository with thousands of engineers collaborating and every commit needs to review.
If I put the entries that are automatically generated by this tool, I have to justify why I need to put some duplicated entries just to make this tool happy. It's not a good reason. The best for this commit will be just to put minimal whatever it needs for the repository which is just the external.

But there are actually no conflicts since I agree in most cases, auto handling is good.
So maybe add a parameter (by default is false) and only disable this behavior when it is true.
Thanks!

**Comment by cpsauer** [comment] 2022-06-22 00:30
Ah! I see. 

Are you using the tool privately, then, keeping the configuration you've set up for it locally, rather than committing that configuration? Or are you partially committing the configuration, but want it to be as minimal as possible?

**Comment by cpsauer** [comment] 2022-06-22 00:51
What I'm thinking:
In either case, I'm not so sure how the setting makes things better--but I'm still open to it.
- If you're using the tool privately, you have changes you aren't going to commit, and this setting wouldn't really reduce or minimize that, sadly. Though maybe there's an opportunity for some kind of no-install mode!
- And if you need to get the change past review, and want to commit everything, I don't think the existing setup would force you to have duplicate entries you don't want. It shouldn't add entries if they're already there, but might save you from entries that are subtly buggy. 
  - (Like, e.g., ignoring `bazel-*` rather than `\bazel-*` from the workspace root might mistakenly catch future subdirectories, or manually specifying the output symlink names will break under certain flags, etc.) That said, if you think that's wrong and there are duplicative entries that would be *better* than the ones we're adding, please say. Like for example, do you have nested compile_commands.json files that you do want to ignore?
  - And ignoring /.cache/ isn't so bad, so you're set in case anyone wants to use clangd! IMO committing that instead of committing an additional line of config seems pretty justifiable.

Cheers,
Chris

**Comment by cpsauer** [comment] 2022-06-29 01:01
@lsmgeb89, since it's been a week, I'm going to (optimistically) close this down, because I'm not seeing how adding the parameter makes things significantly better. 

If I'm wrong, please explain, and I'll open this right back up. Same goes for anyone else reading this issue in the future :)

**Closed** 2022-06-29 01:01 UTC

**Comment by aaron-michaux** [comment] 2022-08-28 15:11
We have an issue where we don't actually use git. So the tool just fails to run, because there's no .gitignore files.

**Comment by cpsauer** [comment] 2022-08-28 22:08
@aaron-michaux, oh gosh, I'm sorry. 

The intended behavior is: detect if git. If not, skip gitignore logic. If so, add necessary items if not already present, creating gitignore iff necessary. So this is definitely bug. My apologies.

On it.

**Comment by cpsauer** [comment] 2022-08-28 22:14
To answer your question:
Where? This logic is operating from the main Bazel workspace root only--next to your WORKSPACE file.

[On the error: Not a big deal, but next time it could be handy to see the exception that was thrown if there was one, not just the backtrace. Also maybe this should be a separate issue, so we don't send too many notifications to the OP, but happy to handle it here.]

**Comment by cpsauer** [comment] 2022-08-28 22:25
Hmm, okay, first logic check:
1. Just to confirm: There is not already a .gitignore in your Bazel workspace root, next to your WORKSPACE file, right?
  a. And to doubly confirm, with the Bazel workspace root as your working directory does `python3 -c 'import os; print(os.path.isfile(".gitignore"))'` print False?
3. When you run `git rev-parse --git-dir`, with your Bazel workspace root as your working directory, what's the output? And is the return code non zero? The goal of this is to check whether the bazel workspace is inside of a git repository, so I'm anticipating a non-zero return code.

[I'm asking because I think one of those must be detecting incorrectly for you to get to the line in question.]

**Comment by cpsauer** [comment] 2022-08-28 23:13
Hmm, and I've just checked exercised the various cases on my computer and haven't managed to reproduce the problem yet. I've tried running {with and without git}x{with and without a gitignore already created} and it seems to do the right thing so far. So I think I'll need your help on some of the above questions.

[Any chance //.gitignore exists on your system, but is write protected or something? Tracking down what's going on in this case that I haven't anticipated is where the exception info (if any), and answers to the above will be super helpful.]

**Comment by cpsauer** [comment] 2022-08-30 00:17
It's always tough booting up on a complicated new codebase! Wishing you good luck @aaron-michaux. (I'm curious what you're working on if you can say!) I'm hoping that, once we patch things here, this tool makes it easier in some small way.

Good to know re perforce. I've used it, but it's been a long time! Most of my experience with that interface was via Google's citc/g3 setups.

IIRC, there might be good ways of having things be modifiable by default for your perforce client that ease pain around this kind of thing more generally. Googling and [linking](https://stackoverflow.com/questions/48195633/prevent-perforce-from-marking-files-as-read-only), just in case it's more generally of use to you.

I wonder if maybe perforce is using that gitignore? [Looks like some people set perforce to load .gitignore](https://stackoverflow.com/questions/18240084/how-does-perforce-ignore-file-syntax-differ-from-gitignore-syntax). If perforce is using the gitignore, you might even want to checkout .gitignore (to make it editable) and let this tool do its (one-time) edit so that the right files are ignored?

^ Basically, I'm wondering if you might want to make .gitignore or other files editable.

If making .gitignore editable isn't something you want to do, I'm also super open to your proposal. Maybe, at the same time, we should ship a simple option to manually disable the gitignore feature? That would make the warning silencable/actionable. I'd be delighted to take a PR for some or all of that, if you want to get on the contributor board. I can also just knock it out.  But by default, I'm holding off for now and suggesting a PR because I think the right solution depends on your setup.

**Comment by cpsauer** [comment] 2023-01-13 21:57
Hey guys! Heads that we no longer write to the .gitignore in source control as of the commit backlinked above! Instead, we provide the same functionality by writing to the hidden gitignore inside the .git directory, making things work without having to worry about modifiability or needing to check in gitignore changes.
