### ISSUE TITLE
invalid syntax while running this tool

### ISSUE THREAD

**Issue by uuuuu-diwu** [hedronvision/bazel-compile-commands-extractor#66] opened 2022-07-08 02:02 UTC
bazel-out/k8-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/hedron_compile_commands/refresh_all.py", line 317
    header_search_process = _search_headers([header_cmd[0], f'@{path}'])
                                                                     ^
SyntaxError: invalid syntax

**Comment by cpsauer** [comment] 2022-07-08 03:51
Hey, @uuuuu-diwu! Thanks for trying the tool and writing in.

Any idea what's wrong with the syntax? 
[I'm having trouble reproducing over here.]

Cheers,
Chris

**Comment by uuuuu-diwu** [comment] 2022-07-08 04:09
it seems not match with my python version ?
more details: 
wudi.hust@n227-029-180:~/work_space/ClionProject/iouring_net/unit_test$ bazelisk run --python_version=PY3  @hedron_compile_commands//:refresh_all
INFO: Build option --cxxopt has changed, discarding analysis cache.
INFO: Analyzed target @hedron_compile_commands//:refresh_all (40 packages loaded, 315 targets configured).
INFO: Found 1 target...
Target @hedron_compile_commands//:refresh_all up-to-date:
  bazel-bin/external/hedron_compile_commands/refresh_all.py
  bazel-bin/external/hedron_compile_commands/refresh_all
INFO: Elapsed time: 0.853s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
  File "/data00/home/wudi.hust/.cache/bazel/_bazel_wudi.hust/ad04a97cc72abe56b74e1df2c06b8308/execroot/__main__/bazel-out/k8-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/hedron_compile_commands/refresh_all.py", line 317
    header_search_process = _search_headers([header_cmd[0], f'@{path}'])
                                                                     ^
SyntaxError: invalid syntax

**Comment by cpsauer** [comment] 2022-07-08 04:28
hmm do you know what python version you're using?
(3.9.13 over here)

I really want to help--I'm just genuinely not sure yet what's wrong with that line. Could I ask you to hop into that file and see if anything looks wrong?

**Comment by cpsauer** [comment] 2022-07-08 05:39
Update: I added a code block to your previous message so I could see where the carrot was pointing. Looks like python thinks the issue is the end quote.
[That's what you'd expect with a version of python that's too old for format strings but there's a check at the top of our file making sure that you have python 3.7 or greater, so I'm still stumped.]

**Comment by uuuuu-diwu** [comment] 2022-07-08 05:48
I upgrade my python3 from python3.5 to python3.10, then everything works.
Thank you for the tool, very useful!

**Comment by cpsauer** [comment] 2022-07-08 05:56
Great! But wait, how did the 3.5 get past that check at the top of the file? If it did (and that line's buggy somehow) then I really want to make sure we fix it.
https://github.com/hedronvision/bazel-compile-commands-extractor/blob/30149bdadf7b1d0b0367592bfb4864318202765d/refresh.template.py#L14

**Comment by cpsauer** [comment] 2022-07-08 05:56
(closing, but I still really want to hear back on the above)

**Closed by cpsauer** 2022-07-08 05:56 UTC
